<?php

class VPageHome extends VPage {
    public function __construct() {
        parent::__construct();
        $this->add(new VRecent());

        $type = [
            "us" => "User",
            "do" => "Domain",
            "co" => "Collection",
            "de" => "Device",
            "ch" => "Channel",
            "ga" => "Gateway",
            "ro" => "Role",
            "se" => "Sequence",
            "st" => "Step",
            "in" => "Instance",
            "pl" => "Plan"];
        foreach ($type as $k => $v) {
            $this->add(new VLink(new VText($v."s"), "/".strtolower($v)."s", "home-link"));
            $this->add(new VText("<br>"));
        }
    }

    public function renderBody() {
        parent::renderBody(); // TODO: Change the autogenerated stub
    }

}