<?php

class VRTRCollection extends VRelTabRow {

    public function __construct(&$model) {
        $sqls=DB::query("SELECT * FROM collections WHERE id=$model->collId");
        $o=$sqls->fetchObject();
        if ($o) {
            $this->add(new VText($o->name));
        } else $this->add(new VText($model->collId));
        parent::__construct($model);
    }

    protected function renderItem(VView $v) {
        parent::renderItem($v); // TODO: Change the autogenerated stub
    }
}