<?php

class VFormFieldBoolean extends VFormField {

    public function renderBody(): void {
        parent::renderBody(); // TODO: Change the autogenerated stub
        echo "<input name='$this->fieldId' type='checkbox'".
            ( ($this->model) ? "checked=\"checked\"" : "" ).
            ( ($this->disabled) ? "disabled=\"disabled\"" : "" )."/>";
    }

    public function registerController(FormContext $c): void {
        parent::registerController($c); // TODO: Change the autogenerated stub
        $c->add(new CBoolean($this->model, $this->fieldId));
    }


}