<?php

class VFormField extends VView {
    protected $fieldId;
    protected $label;
    protected $model;

    public function __construct(&$model = NULL, $label = NULL) {
        $this->model = &$model;
        $this->fieldId = genFieldId();
        $this->label = $label;
    }

    public function renderHeader() {
        parent::renderHeader(); // TODO: Change the autogenerated stub
        if ($this->label) echo "<label for='$this->fieldId'>$this->label</label>";

    }

    public function renderFooter() {
        parent::renderFooter(); // TODO: Change the autogenerated stub
    }


}