<?php

class VFormFieldNumber extends VFormField {

    public function renderBody() {
        parent::renderBody(); // TODO: Change the autogenerated stub
        echo "<input name='$this->fieldId' value='$this->model' type='number'/>";
    }

    public function registerController(ControllerCollection $cc) {
        parent::registerController($cc); // TODO: Change the autogenerated stub
        $cc->add(new CNumber($this->model, $this->fieldId));
    }


}