<?php

class VFormFieldDropdown extends VFormField {
    const Sql = "SELECT * FROM table";
    const PermName = "";
    const LabelColumn = "name";
    const ValueColumn = "id";

    public function __construct(&$model = NULL, $label = NULL) {
        $this->model = &$model;
        $this->fieldId = genFieldId();
        $this->label = $label;
    }

    public function renderHeader(): void {
        parent::renderHeader(); // TODO: Change the autogenerated stub
        echo "<select name='$this->fieldId' />";
    }

    protected function renderBody(): void {
        parent::renderBody(); // TODO: Change the autogenerated stub
        $sql=$this->buildSql();
        error_log($sql);
        $sqls=DB::prepare($sql);
        if (!$sqls->execute([])) die(get_called_class().": SQL Error.");

        $label = static::LabelColumn;
        $value = static::ValueColumn;
        while ($o=$sqls->fetchObject()) {
            echo "<option value='".$o->$value."' ".
                (($this->model == $o->$value) ? "selected=\"selected\"" : "").
                ( ($this->disabled) ? "disabled=\"disabled\"" : "" )."/>"
                .$o->$label."</option>";
        }
        $sqls->closeCursor();
    }


    public function renderFooter(): void {
        echo "</select>";
        parent::renderFooter(); // TODO: Change the autogenerated stub
    }


    public function registerController(FormContext $c): void {
        parent::registerController($c); // TODO: Change the autogenerated stub
        $c->add(new CDropdown($this->model, $this->fieldId));
    }

    protected function buildSql() {
        if (static::PermName !== "") return static::Sql . PermissionManager::arrayToSQL($_SESSION["perms"]->getDomainsByPerm(static::PermName));
        else return static::Sql;
    }

}