<?php

class VFormFieldBoolean extends VFormField {

    public function renderBody() {
        parent::renderBody(); // TODO: Change the autogenerated stub
        echo "<input name='$this->fieldId' type='checkbox'".
            ( ($this->model) ? "checked=\"checked\"" : "" )."/>";
    }

    public function registerController(ControllerCollection $cc) {
        parent::registerController($cc); // TODO: Change the autogenerated stub
        $cc->add(new CBoolean($this->model, $this->fieldId));
    }


}