<?php

class VFormFieldPassword extends VFormField {

    public function renderBody() {
        parent::renderBody(); // TODO: Change the autogenerated stub
        echo "<input name='$this->fieldId' value='' type='password'/>";
    }

    public function registerController(FormContext $c) {
        parent::registerController($c); // TODO: Change the autogenerated stub
        $c->add(new CPassword($this->model, $this->fieldId));
    }


}