<?php

class VFormFieldButton extends VFormField {
    const ButtonType = "submit";
    private $viewContent;
    protected $method;
    protected $argument;

    public function __construct(&$model, $method, $viewContent, $label = NULL, $argument = NULL) {
        parent::__construct($model, $label);
        $this->viewContent = $viewContent;
        $this->method = $method;
        $this->argument = $argument;
    }


    public function renderHeader() {
        parent::renderHeader(); // TODO: Change the autogenerated stub
        echo "<button name='$this->fieldId' value='1' type='".static::ButtonType."'/>";
    }

    public function renderFooter() {
        echo "</button>";
        parent::renderFooter(); // TODO: Change the autogenerated stub
    }

    public function renderBody() {
        $this->viewContent->render();
    }

    public function registerController(ControllerCollection $cc) {
        parent::registerController($cc); // TODO: Change the autogenerated stub
        $cc->add(new CButton($this->model, $this->fieldId, $this->method, $this->argument));
    }


}