<?php

class VFormField extends VView {
    protected $fieldId;
    protected $label;
    protected $model;
    protected $disabled;

    public function __construct(&$model = NULL, $label = NULL) {
        $this->model = &$model;
        $this->fieldId = genFieldId();
        $this->label = $label;
        $this->disabled = false;
    }

    public function renderHeader() : void {
        parent::renderHeader(); // TODO: Change the autogenerated stub
        if ($this->label) echo "<label for='$this->fieldId'>$this->label</label>";

    }

    public function renderFooter() : void {
        parent::renderFooter(); // TODO: Change the autogenerated stub
    }

    public function disable(bool $disabled = true) : VFormField {
        $this->disabled = $disabled;
        return $this;
    }
}