<?php

class VFormFieldButton extends VFormField {
    const ButtonType = "submit";
    private $viewContent;
    protected $method;
    protected $argument;
    protected $htmlClass;

    public function __construct(&$model, $method, $viewContent, $label = NULL, $argument = NULL, $htmlClass = NULL) {
        parent::__construct($model, $label);
        $this->viewContent = $viewContent;
        $this->method = $method;
        $this->argument = $argument;
        $this->htmlClass = $htmlClass;
    }


    public function renderHeader() {
        parent::renderHeader(); // TODO: Change the autogenerated stub
        echo "<button name='$this->fieldId' value='1' type='".static::ButtonType."'".($this->htmlClass ? " class='$this->htmlClass' " : "")."/>";
    }

    public function renderFooter() {
        echo "</button>\n";
        parent::renderFooter(); // TODO: Change the autogenerated stub
    }

    public function renderBody() {
        $this->viewContent->render();
    }

    public function registerController(FormContext $c) {
        parent::registerController($c); // TODO: Change the autogenerated stub
        $c->add(new CButton($this->model, $this->fieldId, $this->method, $this->argument));
    }


}