<?php

class VFormFieldDateTime extends VFormField {

    public function renderBody() {
        parent::renderBody(); // TODO: Change the autogenerated stub
        echo "<input name='$this->fieldId' value='$this->model' type='datetime-local'".
            ( ($this->disabled) ? "disabled=\"disabled\"" : "" )."/>";
    }

    public function registerController(FormContext $c) {
        parent::registerController($c); // TODO: Change the autogenerated stub
        $c->add(new CText($this->model, $this->fieldId));
    }


}