<?php

class VFormFieldNumber extends VFormField {

    public function renderBody(): void {
        parent::renderBody(); // TODO: Change the autogenerated stub
        echo "<input name='$this->fieldId' value='$this->model' type='number'".
            ( ($this->disabled) ? "disabled=\"disabled\"" : "" )."/>";
    }

    public function registerController(FormContext $c): void {
        parent::registerController($c); // TODO: Change the autogenerated stub
        $c->add(new CNumber($this->model, $this->fieldId));
    }


}