<?php

/**
 * View of PageId. Implemented as a hidden field.
 */
class VPageId extends VView {
    /**
     * @const PageId
     * Name of input that stores PageId.
     */
    const PageId='pageId';

    public function renderBody(): void {
        parent::renderBody();
        echo "<input type='hidden' name='".static::PageId."' value='".MObjectModel::getPageId()."' />";
    }

    public function registerController(FormContext $c): void {
        parent::registerController($c); // TODO: Change the autogenerated stub
        $c->add(new CPageId(MObjectModel::getPageId()));
    }
}