<?php

/**
 * View for default table row. This row generates view for single entity.
 */
class VPTableRow extends VList {

    public function __construct($deleteLink = null) {
        if ($deleteLink) $this->add(new VLink(new VIcon("/icon/delete.png", "delete this record"), $deleteLink));
        else $this->add(new VText(""));
    }

    /**
     * Renders single cell of the table.
     * @param VView $v View of single cell of table.
     * @return void
     */
    protected function renderItem(VView $v) {
        echo "<td>";
        parent::renderItem($v); // TODO: Change the autogenerated stub
        echo "</td>\n";
    }


}