<?php
// TODO: POPISKY
/**
 * View for default table. This table's rows show single entity details.
 */
class VTable extends VList {
    /**
     * Creates view for header of the table and adds rows for items passed in $model.
     * @param $model An instance of model MT<type>. Member $items stores an array of MR<type> models.
     * @param $label Not used.
     */
    public function __construct($heading, $removeCol = "", $label = NULL) {
        $this->add(new VTableHeading($heading, $removeCol));
    }
    /**
     * Renders single row of the table.
     * @param VView $v View of single row of table.
     * @return void
     */
    protected function renderItem(VView $v) {
        echo "<tr>\n";
        parent::renderItem($v); // TODO: Change the autogenerated stub
        echo "</tr>\n";
    }

    /**
     * Renders the beginning of the table.
     * @return void
     */
    protected function renderHeader() {
        parent::renderHeader();
        echo "<table>\n";
    }

    /**
     * Renders the end of the table and the button for adding new rows.
     * @return void
     */
    protected function renderFooter() {
        echo "</table>\n";
        parent::renderFooter(); // TODO: Change the autogenerated stub
    }
}