<?php

class MChannel extends MModel {
    public const viewClass = "VFormChannel";
    public $id;
    public $name;
    public $deviceId;
    public $commType;
    public $valueType;
    public $updateFreq;
    private $tmpId;

    public function __construct($id) {
        if($id) {
            $sqls=DB::query("SELECT * FROM channels WHERE id=$id");
            $o=$sqls->fetchObject();
            if($o) {
                $this->id = $o->id;
                $this->name = $o->name;
                $this->deviceId = $o->device_id;
                $this->commType = $o->comm_type;
                $this->valueType = $o->value_type;
                $this->updateFreq = $o->update_freq;
            }
        }
    }

    public function store() {
        if (!parent::store()) return false; // TODO: Change the autogenerated stub
        $sql = $this->id ? "UPDATE" : "INSERT INTO";
        $sql.=" channels SET name=:name, device_id=:device_id, comm_type=:comm_type,".
        " value_type=:value_type, update_freq=:update_freq";
        if ($this->id) $sql.=" WHERE id=$this->id";
        $sqls=DB::prepare($sql);
        if (!$sqls->execute(["name" => $this->name, "device_id" => $this->deviceId,
            "comm_type" => $this->commType, "value_type" => $this->valueType,
            "update_freq" => $this->updateFreq]))
        {
            error_log(get_called_class().": SQL Error.");
            return false;
        }
        if (!$this->id) $this->tmpId = DB::lastInsertId();
        return true;
    }

    public function storeCommit() {
        parent::storeCommit();
        if (!$this->id) $this->id = $this->tmpId;
    }

    public function delete() {
        if(!$this->id) return TRUE;
        $sql = "DELETE FROM channels WHERE id=$this->id";
        if (FALSE===DB::exec($sql)) return FALSE;
        if (FALSE===parent::delete()) return FALSE;
        $this->tmpId = NULL;
        return TRUE;
    }

    public function clickedSubmit() {
        $this->persist();
    }


}