<?php

class MDomain extends MModel {
    public const viewClass = "VFormDomain";
    public $id;
    public $name;
    private $tmpId;

    public function __construct($id) {
        if($id) {
            $sqls=DB::query("SELECT * FROM domains WHERE id=$id");
            $o=$sqls->fetchObject();
            if ($o) {
                $this->id = $o->id;
                $this->name = $o->name;
            }
        }
    }

    public function store() {
        if (!parent::store()) return false; // TODO: Change the autogenerated stub
        $sql = $this->id ? "UPDATE" : "INSERT INTO";
        $sql.=" domains SET name=:name";
        if ($this->id) $sql.=" WHERE id=$this->id";
        $sqls=DB::prepare($sql);
        if (!$sqls->execute(["name" => $this->name]))
        {
            error_log(get_called_class().": SQL Error.");
            return false;
        }
        if (!$this->id) $this->tmpId = DB::lastInsertId();
        return true;
    }

    public function storeCommit() {
        parent::storeCommit();
        if (!$this->id) $this->id = $this->tmpId;
    }

    public function delete() {
        if (!$this->id) return TRUE;
        $sql = "DELETE FROM domains WHERE id=$this->id";
        if (FALSE===DB::exec($sql)) return FALSE;
        if (FALSE===parent::delete()) return FALSE;
        $this->tmpId = NULL;
        return TRUE;
    }

    public function clickedSubmit() {
        $this->persist();
    }


}