<?php

/**
 * @brief Model for login object. This object is used on login page.
 */
class MLogin extends MModel {
    /**
     * @var string $login Username posted by user.
     */
    public $login = "";
    /**
     * @var string $pwdHash Hash of password posted by user.
     */
    public $pwdHash = "";

    /**
     * @brief Tries to find inputted data in database.
     * If successful, sets SESSION variable "loginId" to id of logged-in user.
     * If not, unsets this SESSION variable.
     * @param null $arg Universal argument, not used here.
     * @return bool Check was successful.
     */
    public function store($arg = NULL) {
        if (!parent::store()) return false; // TODO: Change the autogenerated stub
        $sql = "SELECT * from users WHERE login=:login AND pwdhash=:pwdhash";
        $sqls=DB::prepare($sql);
        if (!$sqls->execute(["login" => $this->login,
            "pwdhash" => $this->pwdHash]))
        {
            error_log(get_called_class().": SQL Error.");
            return false;
        }
        $o=$sqls->fetchObject();
        if ($o) {
            header("Location: /");
            $_SESSION["loginId"] = $o->id;
            exit();
        }
        else unset($_SESSION["loginId"]);
        return true;
    }

    /**
     * @brief Used for logging off. Removes SESSION variable loginId.
     * @return bool Removal was successful.
     */
    public function delete($arg = NULL) {
        if(isset($_SESSION["loginId"])) unset($_SESSION["loginId"]);
        return TRUE;
    }

    /**
     * Starts checking process.
     * Called when button in edit form using this model is pressed.
     * @return void
     */
    public function clickedSubmit() {
        $this->persist();
    }


}