<?php

/**
 * @brief Model for sequence object.
 */
class MSequence extends MModel {
    /**
     * @var $id
     * Id of sequence loaded from database.
     */
    public $id;
    /**
     * @var $name
     * Name of sequence loaded from database.
     */
    public $name;
    /**
     * @var $firstStepId
     * Id of first step of sequence loaded from database.
     */
    public $firstStepId;
    /**
     * @var $tmpId
     * Id that is used during storing phase, if storing is successful, $id is set to $tmpId.
     */
    private $tmpId;

    /**
     * Constructs model using data from database.
     * @param $id Id of sequence in database.
     */
    public function __construct($id) {
        if($id) {
            $sqls=DB::query("SELECT * FROM sequences WHERE id=$id");
            $o=$sqls->fetchObject();
            if ($o) {
                $this->id = $o->id;
                $this->name = $o->name;
                $this->firstStepId = $o->first_step_id;
            }
        }
    }

    /**
     * @brief Tries to store data to database.
     * @param null $arg Universal argument, not used here.
     * @return bool Storing was successful.
     */
    public function store(int $arg = 0) {
        if (!parent::store()) return false; // TODO: Change the autogenerated stub
        $sql = $this->id ? "UPDATE" : "INSERT INTO";
        $sql.=" sequences SET name=:name, first_step_id=:first_step_id";
        if ($this->id) $sql.=" WHERE id=$this->id";
        $sqls=DB::prepare($sql);
        $res = true;
        try {
            $res = $sqls->execute(["name" => $this->name, "first_step_id" => $this->firstStepId]);
        } catch (PDOException) {
            $res = false;
        }
        if (!$res) {
            error_log(get_called_class().": SQL Error.");
            return false;
        }
        if (!$this->id) $this->tmpId = DB::lastInsertId();
        else $this->tmpId = $this->id;
        return true;
    }

    /**
     * @brief Used when storing in database was successful. Commits all changes to model and database.
     * @return void
     */
    public function storeCommit() {
        parent::storeCommit();
        if (!$this->id) $this->id = $this->tmpId;
    }

    /**
     * @brief Deletes corresponding record from database.
     * @return bool Deletion was successful.
     */
    public function delete($arg = NULL) {
        if (!$this->id) return TRUE;

        $next = $this->firstStepId;
        while ($next) {
            $sqls = DB::query("SELECT * FROM steps WHERE id=$next");
            $o=$sqls->fetchObject();
            if ($o) {
                $sql = "DELETE FROM steps WHERE id=$next";
                $next = $o->next_step_id;
                if (FALSE===DB::exec($sql)) return FALSE;
            }
        }

        $sql = "DELETE FROM instances WHERE seq_id=$this->id";
        if (FALSE===DB::exec($sql)) return FALSE;

        $sql = "DELETE FROM sequences WHERE id=$this->id";
        if (FALSE===DB::exec($sql)) return FALSE;
        if (FALSE===parent::delete()) return FALSE;
        $this->tmpId = NULL;
        return TRUE;
    }

    /**
     * Starts saving process to database.
     * Called when button in edit form using this model is pressed. Adds notification to user about result.
     * @return void
     */
    public function clickedSubmit() {
        if ($this->persist()) VPageHollow::addNotification(new VNotification(VNotification::NT_Success, "Sequence was saved."));
        else VPageHollow::addNotification(new VNotification(VNotification::NT_Error, "Sequence could not have been saved!"));
    }

    /**
     * Starts deleting process in database.
     * If not successful, reverts changes made. Adds notification to user about result.
     * @return bool
     */
    public function unpersist() {
        $ret = parent::unpersist();
        if ($ret) VPageHollow::addNotification(new VNotification(VNotification::NT_Success, "Sequence was deleted."));
        else VPageHollow::addNotification(new VNotification(VNotification::NT_Error, "Sequence could not have been saved!"));
        return $ret;
    }
}