version: '3'

services:
  nginx:
    image: nginx:1.23.3
    restart: always
    volumes:
      - ./html:/var/www/html/:ro
      - ./conf:/etc/nginx/conf.d/:ro
    ports:
      - 80:80
    networks:
      - internal
  php:
    image: dandadin/iothome-php:8.3.4
#    image: test:latest
    restart: always
    networks:
      - internal
    volumes:
      - ./php:/var/www/html/
  db:
    image: mysql:8.0.32
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: 'root-heslo'
    ports:
      - 3366:3306
  adminer:
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - internal
    ports:
      - 8888:8080
  executor:
    image: busybox:1.36.1
    command: /executor
    restart: always
    networks:
      - internal
    volumes:
      - ./executor:/executor
networks:
  internal:
    driver: bridge

