#!/bin/sh

PORT=9999	# trigger port

nc -kl  -p $PORT -e kill -USR1 $$ &	# TCP
nc -klu -p $PORT -e kill -USR1 $$ &	# UDP

trap 'echo TRIGGER;kill $sl_pid' USR1	# signal from nc
trap 'exit' TERM			# graceful shutdown

while true
do
   DELAY=$(wget -O - -q http://iothome.cz/execute)
   echo "[$$]sleeping $DELAY s"
   [ -z "$DELAY" ] && DELAY=1
   [ "$DELAY" = 0 ] && DELAY=1
   sleep $DELAY &
   sl_pid=$!
   wait $sl_pid
done
